- category: Custom Music
  songs:
    - name: "All Over You.mp3"
      length: -1
    - name: "Shark Baby Attack (2).mp3"
      length: -1
    - name: "Simp, Mark, Simp!.mp3"
      length: -1
    - name: "Slop (2).mp3"
      length: -1
    - name: "Visiting her Pale.mp3"
      length: -1
